// All the constants in the application
const constants = {
  APP_NAME : 'TO THE LOO...',
  SHOW_WAY: 'Show me the way',
  HATE_MAPS: 'Hate maps? Use your camera to find your way',
  LIVE_GUIDE: 'LIVE GUIDE',
  AMENITY_DETAILS: 'See amenity details',
  NOT_AVAILABLE: 'oops..! The Loos are closed due to maintainance for a while. Please try again later.',
  BASE_URL: 'http://localhost:8081/',
  WAY: 'SHOW ME THE WAY',
  AMENITY_TITLE: 'Amenity details',
  FACILITIES_PROVIDED: 'Facilities Provided',
  CLEANING_INFO: 'Cleaning Information',
  LAST_CLEANED: 'LAST CLEANED',
  LIVE: '*Live update',
  DEFAULTCATEGORY: 4,
  AMINITIES_PROVIDED: 'Amenities provided',
  CONTACT_US: 'Contact Us',
  OPEN_MENU: 'open-menu',
  CLOSE_MENU: 'close-menu',
  PARENT_ID: 4,
  ACCESSIBLE_ID: 3,
  LADIES_ID: 1,
  MENS_ID: 2,
  LOODETAILS: 'looDetails',
  AMINITYDETAILS: 'aminityDetails',
  CATEGORIES: 'categories',
};
export default constants;
